version: '3.7'
services:
    nginx:
        container_name: nginx
        build:
            context: ./nginx
            dockerfile: Dockerfile
        depends_on:
            - api
        ports:
            - 80:80
            - 443:443
        volumes:
            - ~/../assets:/usr/share/nginx/assets/
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf
            - ~/etc/letsencrypt:/etc/letsencrypt
    api:
        container_name: api
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - ~/../assets:/usr/assets
        env_file: 
            ./.env
